spring.application.name=backend
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://143.106.241.3:3306/cl203108
spring.datasource.username=cl203108
spring.datasource.password=cl*29082007
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true
server.port=8080 